package com.venturelens.model;

import java.awt.Color;

/**
 * Standard Decision Tiers generated by the VentureLens NLP Validation Engine.
 * - STRONG_GO (>= 80): High market demand, defensible moat, clear feasibility.
 * - GO (65-79): Viable opportunity with addressable competition and acceptable risk.
 * - CAUTION (50-64): Borderline concept; significant weaknesses or negative sentiment markers.
 * - PIVOT (< 50): High failure probability, crowded commoditized market, or fatal bottlenecks.
 */
public enum DecisionTier {
    STRONG_GO("Strong Go", new Color(0x10, 0xB9, 0x81), new Color(0x06, 0x4E, 0x3B)),
    GO("Go", new Color(0x3B, 0x82, 0xF6), new Color(0x1E, 0x3A, 0x8A)),
    CAUTION("Caution", new Color(0xF5, 0x9E, 0x0B), new Color(0x78, 0x35, 0x0F)),
    PIVOT("Pivot", new Color(0xEF, 0x44, 0x44), new Color(0x7F, 0x1D, 0x1D));

    private final String label;
    private final Color badgeColor;
    private final Color darkBackground;

    DecisionTier(String label, Color badgeColor, Color darkBackground) {
        this.label = label;
        this.badgeColor = badgeColor;
        this.darkBackground = darkBackground;
    }

    public String getLabel() {
        return label;
    }

    public Color getBadgeColor() {
        return badgeColor;
    }

    public Color getDarkBackground() {
        return darkBackground;
    }

    public static DecisionTier fromScore(double overallScore) {
        if (overallScore >= 80.0) {
            return STRONG_GO;
        } else if (overallScore >= 65.0) {
            return GO;
        } else if (overallScore >= 50.0) {
            return CAUTION;
        } else {
            return PIVOT;
        }
    }

    public static DecisionTier fromString(String tierName) {
        if (tierName == null) return CAUTION;
        try {
            return DecisionTier.valueOf(tierName.trim().toUpperCase());
        } catch (IllegalArgumentException e) {
            return CAUTION;
        }
    }
}
