package com.venturelens.ui;

import com.venturelens.model.CapTableState;
import com.venturelens.model.FinancialLedger;
import com.venturelens.model.VentureIdea;

import java.io.BufferedWriter;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 * Pure standard java.io and java.nio.file exporter for VentureLens.
 * Generates:
 * 1. Structured Markdown Pitch Outline (.md)
 * 2. Printable HTML/CSS Document (.html) with @media print rules for instant browser-to-PDF export.
 */
public class PitchDeckExporter {

    private static final DecimalFormat CURRENCY = new DecimalFormat("$#,##0");
    private static final DecimalFormat PCT = new DecimalFormat("#0.0'%'");

    /**
     * Exports a structured 10-slide startup pitch blueprint to a Markdown file.
     */
    public static void exportToMarkdown(File targetFile, VentureIdea idea, CapTableState capTable, FinancialLedger ledger) throws IOException {
        StringBuilder sb = new StringBuilder();
        String dateStr = LocalDate.now().format(DateTimeFormatter.ofPattern("MMMM d, yyyy"));

        sb.append("# ").append(idea.getStartupName()).append(" — Executive Pitch Deck Blueprint\n");
        sb.append("**Generated by VentureLens Operating System** | ").append(dateStr).append("\n\n");
        sb.append("---\n\n");

        sb.append("## Executive Scorecard\n");
        sb.append("- **Decision Tier:** ").append(idea.getDecisionTier().getLabel()).append("\n");
        sb.append("- **Composite Validation Score:** ").append(idea.getOverallScore()).append("/100\n");
        sb.append("- **Market Demand Score:** ").append(idea.getMarketScore()).append("/100\n");
        sb.append("- **Technical Feasibility Score:** ").append(idea.getFeasibilityScore()).append("/100\n");
        sb.append("- **Competitive Defensibility Score:** ").append(idea.getCompetitionScore()).append("/100\n\n");

        sb.append("### Slide 1: Title & Hook\n");
        sb.append("**").append(idea.getStartupName()).append("**\n");
        sb.append("*Empowering ").append(idea.getTargetCustomer()).append("*\n\n");

        sb.append("### Slide 2: The Core Problem\n");
        sb.append(idea.getProblemStatement()).append("\n\n");

        sb.append("### Slide 3: Proposed Solution & Value Proposition\n");
        sb.append(idea.getProposedSolution()).append("\n\n");

        sb.append("### Slide 4: Target Market & Ideal Customer Profile (ICP)\n");
        sb.append("- Target Customer: ").append(idea.getTargetCustomer()).append("\n");
        sb.append("- Business Model: ").append(idea.getBusinessModel()).append("\n\n");

        sb.append("### Slide 5: Strategic SWOT Matrix\n");
        sb.append("**Strengths:**\n");
        for (String s : idea.getStrengths()) sb.append("- ").append(s).append("\n");
        sb.append("\n**Weaknesses:**\n");
        for (String w : idea.getWeaknesses()) sb.append("- ").append(w).append("\n");
        sb.append("\n**Opportunities:**\n");
        for (String o : idea.getOpportunities()) sb.append("- ").append(o).append("\n");
        sb.append("\n**Threats:**\n");
        for (String t : idea.getThreats()) sb.append("- ").append(t).append("\n\n");

        sb.append("### Slide 6: Risk Analysis & Mitigation\n");
        for (String r : idea.getRisks()) sb.append("- ").append(r).append("\n");
        sb.append("\n");

        sb.append("### Slide 7: CapTable & Equity Structure\n");
        if (capTable != null) {
            sb.append("- Pre-Money Valuation: ").append(CURRENCY.format(capTable.getPreMoneyValuation())).append("\n");
            sb.append("- Target Investment Round: ").append(CURRENCY.format(capTable.getInvestmentAmount())).append("\n");
            sb.append("- Post-Money Valuation: ").append(CURRENCY.format(capTable.getPostMoneyValuation())).append("\n");
            sb.append("- Founder 1 Diluted Share: ").append(PCT.format(capTable.getFounder1DilutedPct())).append("\n");
            sb.append("- Founder 2 Diluted Share: ").append(PCT.format(capTable.getFounder2DilutedPct())).append("\n");
            sb.append("- ESOP Option Pool: ").append(PCT.format(capTable.getEsopDilutedPct())).append("\n");
            sb.append("- New Investor Ownership: ").append(PCT.format(capTable.getInvestorOwnershipPct())).append("\n\n");
        } else {
            sb.append("*Equity allocation baseline pending round finalization.*\n\n");
        }

        sb.append("### Slide 8: BurnWatch & Financial Runway\n");
        if (ledger != null) {
            sb.append("- Current Cash Balance: ").append(CURRENCY.format(ledger.getStartingCashBalance())).append("\n");
            sb.append("- Total Monthly Expenses: ").append(CURRENCY.format(ledger.getTotalMonthlyExpenses())).append("\n");
            sb.append("- Monthly Contract Revenue: ").append(CURRENCY.format(ledger.getTotalMonthlyRevenue())).append("\n");
            sb.append("- Net Monthly Burn: ").append(CURRENCY.format(ledger.getNetMonthlyBurn())).append("\n");
            sb.append("- Calculated Survival Runway: ").append(String.format("%.1f", ledger.getRunwayMonths())).append(" months\n");
            sb.append("- Projected Zero-Cash Date: ").append(ledger.getZeroCashDateEstimate()).append("\n\n");
        } else {
            sb.append("*Financial runway projections pending ledger entry.*\n\n");
        }

        sb.append("### Slide 9: Milestones & Product Roadmap\n");
        sb.append("- Phase 1 (0-3 Months): Complete MVP validation with pilot design partners.\n");
        sb.append("- Phase 2 (3-6 Months): Achieve SOC2 compliance & initiate enterprise outbound sales.\n");
        sb.append("- Phase 3 (6-12 Months): Expand customer success team & scale to $50k MRR.\n\n");

        sb.append("### Slide 10: The Ask & Investment Terms\n");
        if (capTable != null) {
            sb.append("Seeking **").append(CURRENCY.format(capTable.getInvestmentAmount()))
              .append("** in Seed Preferred Financing to accelerate product engineering and go-to-market execution.\n");
        } else {
            sb.append("Seeking seed investment to accelerate product engineering and go-to-market execution.\n");
        }

        try (BufferedWriter writer = Files.newBufferedWriter(targetFile.toPath(), StandardCharsets.UTF_8)) {
            writer.write(sb.toString());
        }
    }

    /**
     * Exports a styled, printable HTML presentation with @media print CSS rules.
     */
    public static void exportToPrintableHtml(File targetFile, VentureIdea idea, CapTableState capTable, FinancialLedger ledger) throws IOException {
        StringBuilder html = new StringBuilder();
        String dateStr = LocalDate.now().format(DateTimeFormatter.ofPattern("MMMM d, yyyy"));

        html.append("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
        html.append("<meta charset=\"UTF-8\">\n");
        html.append("<title>").append(idea.getStartupName()).append(" — Pitch Deck Blueprint</title>\n");
        html.append("<style>\n");
        html.append("  * { box-sizing: border-box; margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; }\n");
        html.append("  body { background: #0B1320; color: #F1F5F9; padding: 40px; }\n");
        html.append("  .slide { background: #162235; border: 1px solid #273852; border-radius: 12px; padding: 36px; margin-bottom: 32px; page-break-inside: avoid; }\n");
        html.append("  .slide-header { font-size: 13px; text-transform: uppercase; letter-spacing: 1px; color: #10B981; font-weight: 700; margin-bottom: 12px; }\n");
        html.append("  h1 { font-size: 32px; color: #F1F5F9; margin-bottom: 8px; }\n");
        html.append("  h2 { font-size: 24px; color: #F1F5F9; margin-bottom: 16px; }\n");
        html.append("  p { font-size: 15px; line-height: 1.6; color: #CBD5E1; margin-bottom: 16px; }\n");
        html.append("  .badge { display: inline-block; padding: 6px 14px; border-radius: 20px; font-weight: 700; font-size: 14px; margin-bottom: 20px; }\n");
        html.append("  .badge-go { background: #064E3B; color: #10B981; border: 1px solid #10B981; }\n");
        html.append("  .grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }\n");
        html.append("  .grid-4 { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }\n");
        html.append("  .swot-box { background: #0E1828; border: 1px solid #273852; border-radius: 8px; padding: 16px; }\n");
        html.append("  .swot-title { font-weight: 700; font-size: 14px; margin-bottom: 8px; color: #10B981; }\n");
        html.append("  ul { padding-left: 20px; color: #CBD5E1; font-size: 14px; line-height: 1.6; }\n");
        html.append("  li { margin-bottom: 6px; }\n");
        html.append("  .stat-card { background: #0E1828; border-radius: 8px; padding: 14px; border: 1px solid #273852; }\n");
        html.append("  .stat-label { font-size: 12px; color: #94A3B8; margin-bottom: 4px; }\n");
        html.append("  .stat-value { font-size: 20px; font-weight: 700; color: #10B981; }\n");
        html.append("  @media print {\n");
        html.append("    body { background: white !important; color: black !important; padding: 0 !important; }\n");
        html.append("    .slide { background: white !important; color: black !important; border: 1px solid #ccc !important; page-break-after: always; margin-bottom: 0 !important; border-radius: 0 !important; box-shadow: none !important; }\n");
        html.append("    .swot-box, .stat-card { background: #f8fafc !important; border-color: #e2e8f0 !important; color: black !important; }\n");
        html.append("    h1, h2 { color: black !important; }\n");
        html.append("    p, ul, li { color: #334155 !important; }\n");
        html.append("  }\n");
        html.append("</style>\n</head>\n<body>\n");

        // Slide 1: Cover
        html.append("<div class=\"slide\">\n");
        html.append("  <div class=\"slide-header\">Slide 1 of 10 &bull; Executive Summary</div>\n");
        html.append("  <h1>").append(idea.getStartupName()).append("</h1>\n");
        html.append("  <p style=\"font-size: 18px; color: #94A3B8;\">Target Market: ").append(idea.getTargetCustomer()).append("</p>\n");
        html.append("  <span class=\"badge badge-go\">Decision Intelligence: ").append(idea.getDecisionTier().getLabel()).append(" (Score: ").append(idea.getOverallScore()).append("/100)</span>\n");
        html.append("  <p>Engineered using VentureLens Startup Operating System &bull; ").append(dateStr).append("</p>\n");
        html.append("</div>\n");

        // Slide 2: Problem
        html.append("<div class=\"slide\">\n");
        html.append("  <div class=\"slide-header\">Slide 2 of 10 &bull; The Problem</div>\n");
        html.append("  <h2>Critical Industry Pain Point</h2>\n");
        html.append("  <p>").append(idea.getProblemStatement()).append("</p>\n");
        html.append("</div>\n");

        // Slide 3: Solution
        html.append("<div class=\"slide\">\n");
        html.append("  <div class=\"slide-header\">Slide 3 of 10 &bull; The Solution</div>\n");
        html.append("  <h2>Architected Value Proposition</h2>\n");
        html.append("  <p>").append(idea.getProposedSolution()).append("</p>\n");
        html.append("</div>\n");

        // Slide 4: SWOT
        html.append("<div class=\"slide\">\n");
        html.append("  <div class=\"slide-header\">Slide 4 of 10 &bull; Strategic SWOT Analysis</div>\n");
        html.append("  <h2>System-Evaluated SWOT Matrix</h2>\n");
        html.append("  <div class=\"grid-4\">\n");

        html.append("    <div class=\"swot-box\"><div class=\"swot-title\">Strengths</div><ul>");
        for (String s : idea.getStrengths()) html.append("<li>").append(s).append("</li>");
        html.append("</ul></div>\n");

        html.append("    <div class=\"swot-box\"><div class=\"swot-title\" style=\"color:#EF4444;\">Weaknesses</div><ul>");
        for (String w : idea.getWeaknesses()) html.append("<li>").append(w).append("</li>");
        html.append("</ul></div>\n");

        html.append("    <div class=\"swot-box\"><div class=\"swot-title\" style=\"color:#3B82F6;\">Opportunities</div><ul>");
        for (String o : idea.getOpportunities()) html.append("<li>").append(o).append("</li>");
        html.append("</ul></div>\n");

        html.append("    <div class=\"swot-box\"><div class=\"swot-title\" style=\"color:#F59E0B;\">Threats</div><ul>");
        for (String t : idea.getThreats()) html.append("<li>").append(t).append("</li>");
        html.append("</ul></div>\n");

        html.append("  </div>\n");
        html.append("</div>\n");

        // Slide 5: CapTable
        html.append("<div class=\"slide\">\n");
        html.append("  <div class=\"slide-header\">Slide 5 of 10 &bull; CapTable & Financing</div>\n");
        html.append("  <h2>Equity Allocation & Dilution Structure</h2>\n");
        if (capTable != null) {
            html.append("  <div class=\"grid-2\">\n");
            html.append("    <div class=\"stat-card\"><div class=\"stat-label\">Pre-Money Valuation</div><div class=\"stat-value\">").append(CURRENCY.format(capTable.getPreMoneyValuation())).append("</div></div>\n");
            html.append("    <div class=\"stat-card\"><div class=\"stat-label\">Target Seed Round</div><div class=\"stat-value\">").append(CURRENCY.format(capTable.getInvestmentAmount())).append("</div></div>\n");
            html.append("    <div class=\"stat-card\"><div class=\"stat-label\">Post-Money Valuation</div><div class=\"stat-value\">").append(CURRENCY.format(capTable.getPostMoneyValuation())).append("</div></div>\n");
            html.append("    <div class=\"stat-card\"><div class=\"stat-label\">Investor Ownership</div><div class=\"stat-value\">").append(PCT.format(capTable.getInvestorOwnershipPct())).append("</div></div>\n");
            html.append("  </div>\n");
        }
        html.append("</div>\n");

        // Slide 6: Runway
        html.append("<div class=\"slide\">\n");
        html.append("  <div class=\"slide-header\">Slide 6 of 10 &bull; BurnWatch Financials</div>\n");
        html.append("  <h2>Cash Runway & Capital Efficiency</h2>\n");
        if (ledger != null) {
            html.append("  <div class=\"grid-2\">\n");
            html.append("    <div class=\"stat-card\"><div class=\"stat-label\">Cash Balance</div><div class=\"stat-value\">").append(CURRENCY.format(ledger.getStartingCashBalance())).append("</div></div>\n");
            html.append("    <div class=\"stat-card\"><div class=\"stat-label\">Net Monthly Burn</div><div class=\"stat-value\">").append(CURRENCY.format(ledger.getNetMonthlyBurn())).append("</div></div>\n");
            html.append("    <div class=\"stat-card\"><div class=\"stat-label\">Survival Runway</div><div class=\"stat-value\">").append(String.format("%.1f", ledger.getRunwayMonths())).append(" Months</div></div>\n");
            html.append("    <div class=\"stat-card\"><div class=\"stat-label\">Zero-Cash Date</div><div class=\"stat-value\">").append(ledger.getZeroCashDateEstimate()).append("</div></div>\n");
            html.append("  </div>\n");
        }
        html.append("</div>\n");

        // Slide 7: Business Model
        html.append("<div class=\"slide\">\n");
        html.append("  <div class=\"slide-header\">Slide 7 of 10 &bull; Monetization</div>\n");
        html.append("  <h2>Business Model & Pricing Engine</h2>\n");
        html.append("  <p>").append(idea.getBusinessModel()).append("</p>\n");
        html.append("</div>\n");

        // Slide 8: Risks
        html.append("<div class=\"slide\">\n");
        html.append("  <div class=\"slide-header\">Slide 8 of 10 &bull; Risk Mitigation</div>\n");
        html.append("  <h2>Critical Failure Modes & Defenses</h2>\n");
        html.append("  <ul>\n");
        for (String r : idea.getRisks()) html.append("    <li>").append(r).append("</li>\n");
        html.append("  </ul>\n");
        html.append("</div>\n");

        // Slide 9: Milestones
        html.append("<div class=\"slide\">\n");
        html.append("  <div class=\"slide-header\">Slide 9 of 10 &bull; Growth Milestones</div>\n");
        html.append("  <h2>Execution Roadmap</h2>\n");
        html.append("  <p><strong>Q1:</strong> Finalize MVP telemetry core and secure 5 design partner contracts.</p>\n");
        html.append("  <p><strong>Q2:</strong> Expand engineering team and automate multi-cloud agent distribution.</p>\n");
        html.append("  <p><strong>Q3-Q4:</strong> Scale to $50,000 MRR and achieve SOC2 Type II compliance.</p>\n");
        html.append("</div>\n");

        // Slide 10: The Ask
        html.append("<div class=\"slide\">\n");
        html.append("  <div class=\"slide-header\">Slide 10 of 10 &bull; The Investment Opportunity</div>\n");
        html.append("  <h2>Join Us as an Early Strategic Partner</h2>\n");
        if (capTable != null) {
            html.append("  <p style=\"font-size: 18px;\">Raising <strong>").append(CURRENCY.format(capTable.getInvestmentAmount())).append("</strong> to deploy capital into core engineering, customer success, and scale our high-margin enterprise footprint.</p>\n");
        }
        html.append("</div>\n");

        html.append("</body>\n</html>\n");

        try (BufferedWriter writer = Files.newBufferedWriter(targetFile.toPath(), StandardCharsets.UTF_8)) {
            writer.write(html.toString());
        }
    }
}
